import time;
start_time = time.time()
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
print("Hello my french")
end_time = time.time()
execution_time = end_time - start_time
print(f"Execution time: {execution_time} seconds")
# bytecode
